// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpsaqcpwdsopfrzlnjta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwc2FxY3B3ZHNvcGZyemxuanRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzA4MzMsImV4cCI6MjA3MDUwNjgzM30.6upWehvv8xA1rqLbRmq-pfX1eaJ5cNc8_McbHT2X0q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});